### ISSUE TITLE
can you share some English language paper about this Guided learning ?

### ISSUE THREAD

**Issue by Sandy4321** [ChuanyuXue/KDDCUP-2020#1]
great code thanks

in this blog
https://zhuanlan.zhihu.com/p/149424540

you referencing to 

^ Guided learning  https://blog.csdn.net/qq_16234613/article/details/84861240

where you mentioned 
Guided learning 

can you share some English language paper about this Guided learning ?

![image](https://user-images.githubusercontent.com/11426119/85478905-1a077780-b58b-11ea-8ea4-59572f5c986a.png)

![image](https://user-images.githubusercontent.com/11426119/85478967-3c999080-b58b-11ea-9efd-60aab4e12a20.png)

**Comment by ChuanyuXue** [comment]
Hi,

As I know, there is no formal English paper about Guided Learning as it is a new idea provided by data mining competition-er in feature engineering. This technology is fundamentally a useful feature which successfully represents the difference in data distribution. You may find more some introduction about Guided Learning in kaggle or Tianchi platform.

Thanks.

**Comment by Sandy4321** [comment]
my guess it is not this 
https://books.google.ca/books?id=8TrNBQAAQBAJ&pg=PA142&lpg=PA142&dq=%22Guided+Learning%22+feature+selection&source=bl&ots=RL2Tmz9l56&sig=ACfU3U1928Nj5zfqINU0_7Se6wm7NvUs0w&hl=en&sa=X&ved=2ahUKEwiHrfaX2JrqAhWel3IEHXSUDqMQ6AEwA3oECAoQAQ#v=onepage&q=%22Guided%20Learning%22%20feature%20selection&f=false
![image](https://user-images.githubusercontent.com/11426119/85581230-6776f980-b60a-11ea-9db8-1048a8734d82.png)

**Comment by Sandy4321** [comment]
it is not this as well
http://www.jmlr.org/papers/volume3/perkins03a/perkins03a.pdf

At each iteration, a fast gradient-based heuristic is used to quickly assess
which feature is most likely to improve the existing model, that feature is then added to the model,
and the model is incrementally optimized using gradient descent.

**Comment by Sandy4321** [comment]
this search 
"Guided Learning"   site: https://tianchi.aliyun.com/

gives nothing
1
can you share English description
2
or can you specify which file/ lines in your code implement  this "Guided Learning"

**Comment by ChuanyuXue** [comment]
Thank you for your sharing! 

For your questions:

1. As I mentioned, guided learning is a feature engineering technology to alleviate the problem that data distribution is various in one dataset by generating features to represent the distribution for each data-batch. 

For example, in this competition, we have data from different batch divided by time periods[so called "phase" in this competition] with large distribution gap. **We extract features like "item counts in each phase" e.t. to represent the difference in data distribution, so we can put data from all phases into one model and achieve better results.** To put it simply, only using the "label of phase" as a feature can also bring some improvement, even though it now seems as a good feature but it does represent the difference in data distribution as what we called guided learning technology :)

2. File 

- /KDDCUP-2020/code/4_RankFeature/07_count_detail_model1.py
- /KDDCUP-2020/code/4_RankFeature/07_count_detail_model1.py
- /KDDCUP-2020/code/4_RankFeature/07_count_detail_model1.py

implement the guided learning technology.
