### ISSUE TITLE
能提供一下比赛数据的网盘地址吗，比赛已经结束，不能下载数据了，谢谢！！！

### ISSUE THREAD

**Issue by Hanlos** [ChuanyuXue/KDDCUP-2020#2]

**Comment by ChuanyuXue** [comment]
Hi，

你好。今晚我上传到网盘，传完给你发链接。

**Comment by ChuanyuXue** [comment]
underexpose_train.zip | 271.62MB | d2ee53319cce2553c302be64370dd8dc | China | http://tianchi-competition.oss-cn-hangzhou.aliyuncs.com/231785/underexpose_train.zip

underexpose_test.zip | 3.27MB | af0ce14ab317605be7ff953021bed8a2 | China | http://tianchi-competition.oss-cn-hangzhou.aliyuncs.com/231785/underexpose_test.zip

**Comment by ChuanyuXue** [comment]
Please download at above links.

**Comment by Hanlos** [comment]
谢谢🙏




| |
解力勋
邮箱：lixunxie@126.com
|

签名由 网易邮箱大师 定制

在2020年06月28日 14:20，Chuanyu Xue 写道：

Closed #2.
